### ISSUE TITLE
Doesn't get past title screen

### ISSUE THREAD

**Issue by MagnusStrom** [kckarnige/fnf-week-7-code#2]
I slapped this in over my itch build and when i press enter the enter animation just loops.

**Comment by MagnusStrom** [comment]
theres also... no characters... in these files? ok

**Comment by kckarnige** [comment]
DO NOT USE THIS, this is just for people who wanna peek into the files, it's not meant to be played

**Comment by ghost** [comment]
wait zeptos, what brings you here?
