### ISSUE TITLE
Make it more clear that this is NOT uncompiled Haxe code, as that is currently unobtainable.

### ISSUE THREAD

**Issue by Hyperboid** [kckarnige/fnf-week-7-code#4]
Currently, it's easy for someone on an online forum like GameBannana to trick others (even accidentally) into thinking that they could poke around in raw source code to their heart's content.

The solution? I propose something like this at the top of the README:

## STOP!
This is a repository containing the **compiled scripts** of FnF week 7. You will only be able to look at assets (text, audio, images), the game logic is completely unreadable in this current state.

**Comment by Hyperboid** [comment]
"WAIT!" would also work just as well.

**Comment by kckarnige** [comment]
Thanks for the idea, I put a big ass header so yeh
